# Generated by Django on 2026-04-24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0009_enhanced_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('farm_type', models.CharField(choices=[('CATTLE', 'Qoramol ferma'), ('SHEEP', "Qo'y ferma"), ('GOAT', 'Echki ferma'), ('HORSE', 'Ot ferma'), ('CAMEL', 'Tuya ferma'), ('MIXED', 'Aralash ferma')], default='MIXED', max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('mfy', models.CharField(blank=True, max_length=100)),
                ('area_hectares', models.FloatField(default=0, help_text='Ferma maydoni (gektar)')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartcity_app.coordinate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='smartcity_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('microchip_id', models.CharField(help_text='Microchip identifikator raqami', max_length=50, unique=True)),
                ('animal_type', models.CharField(choices=[('CATTLE', 'Qoramol'), ('SHEEP', "Qo'y"), ('GOAT', 'Echki'), ('HORSE', 'Ot'), ('CAMEL', 'Tuya')], max_length=20)),
                ('breed', models.CharField(help_text='Zoti', max_length=100)),
                ('name', models.CharField(blank=True, help_text='Hayvon nomi (ixtiyoriy)', max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Erkak'), ('FEMALE', "Urg'ochi")], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight_kg', models.FloatField(default=0, help_text='Vazni (kg)')),
                ('color', models.CharField(blank=True, help_text='Rangi', max_length=50)),
                ('health_status', models.CharField(choices=[('HEALTHY', "Sog'lom"), ('SICK', 'Kasal'), ('QUARANTINE', 'Karantin'), ('VACCINATED', 'Emlangan'), ('TREATMENT', 'Davolanmoqda')], default='HEALTHY', max_length=20)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('last_vet_check', models.DateField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='smartcity_app.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LivestockPassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('issuing_authority', models.CharField(help_text='Bergan tashkilot', max_length=255)),
                ('origin_region', models.CharField(blank=True, max_length=100)),
                ('origin_district', models.CharField(blank=True, max_length=100)),
                ('mother_microchip_id', models.CharField(blank=True, help_text='Onasi microchip ID', max_length=50)),
                ('father_microchip_id', models.CharField(blank=True, help_text='Otasi microchip ID', max_length=50)),
                ('vaccination_history', models.JSONField(default=list, help_text='Emlash tarixi')),
                ('disease_history', models.JSONField(default=list, help_text='Kasallik tarixi')),
                ('weight_history', models.JSONField(default=list, help_text="Vazn o'zgarish tarixi")),
                ('transfer_history', models.JSONField(default=list, help_text="Egasi o'zgarish tarixi")),
                ('additional_info', models.JSONField(default=dict, help_text="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('livestock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='smartcity_app.livestock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MicrochipDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chip_id', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('implant_date', models.DateField(blank=True, null=True)),
                ('implant_location', models.CharField(blank=True, help_text="Qo'yilgan joy (masalan: chap quloq)", max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Faol'), ('INACTIVE', 'Nofaol'), ('DAMAGED', 'Buzilgan'), ('LOST', "Yo'qolgan")], default='ACTIVE', max_length=20)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.FloatField(default=100, help_text='Batareya darajasi (%)')),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microchip', to='smartcity_app.livestock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
